### ISSUE TITLE
Wront image name in the guide

### ISSUE THREAD

**Issue by LeonXBB** [epwalsh/docker-celery#1]
Hi. I know, this repository is 5 years old, but just in case.

In the guide there is the instruction to `docker pull epwalsh/celery`, however the correct name of the image is (per https://hub.docker.com/r/epwalsh/docker-celery) `epwalsh/docker-celery`. The original name raises an exception while trying to pull it from my terminal. 

Hope it helps someone.

**Comment by epwalsh** [comment]
Thank you! Fixed
